// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Votetype int32

const (
	Votetype_prevote   Votetype = 0
	Votetype_precommit Votetype = 1
)

var Votetype_name = map[int32]string{
	0: "prevote",
	1: "precommit",
}

var Votetype_value = map[string]int32{
	"prevote":   0,
	"precommit": 1,
}

func (x Votetype) String() string {
	return proto.EnumName(Votetype_name, int32(x))
}

func (Votetype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type Proposal struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                uint32   `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Timestamp            uint64   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	PubKeyBytes          []byte   `protobuf:"bytes,5,opt,name=pub_key_bytes,json=pubKeyBytes,proto3" json:"pub_key_bytes,omitempty"`
	Signature            []byte   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Proposal) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Proposal) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Proposal) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Proposal) GetPubKeyBytes() []byte {
	if m != nil {
		return m.PubKeyBytes
	}
	return nil
}

func (m *Proposal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Vote struct {
	Type                 Votetype  `protobuf:"varint,1,opt,name=type,proto3,enum=message.Votetype" json:"type,omitempty"`
	Height               uint64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round                uint32    `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Timestamp            uint64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Proposal             *Proposal `protobuf:"bytes,5,opt,name=proposal,proto3" json:"proposal,omitempty"`
	PubKeyBytes          []byte    `protobuf:"bytes,6,opt,name=pub_key_bytes,json=pubKeyBytes,proto3" json:"pub_key_bytes,omitempty"`
	Signature            []byte    `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetType() Votetype {
	if m != nil {
		return m.Type
	}
	return Votetype_prevote
}

func (m *Vote) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Vote) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Vote) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Vote) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *Vote) GetPubKeyBytes() []byte {
	if m != nil {
		return m.PubKeyBytes
	}
	return nil
}

func (m *Vote) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("message.Votetype", Votetype_name, Votetype_value)
	proto.RegisterType((*Proposal)(nil), "message.proposal")
	proto.RegisterType((*Vote)(nil), "message.vote")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xcd, 0x96, 0xb5, 0xdb, 0xa9, 0x95, 0x19, 0x44, 0x72, 0xe1, 0x45, 0x29, 0x28, 0x45,
	0x70, 0x17, 0xfa, 0x06, 0xde, 0x7a, 0xd7, 0x17, 0x18, 0xa9, 0x3b, 0x74, 0x45, 0xbb, 0x84, 0xe4,
	0x54, 0xe8, 0x3b, 0xf9, 0x64, 0x3e, 0x85, 0x24, 0xae, 0x74, 0x4c, 0x65, 0x77, 0xfd, 0xff, 0x8f,
	0x26, 0xe7, 0x3b, 0x81, 0xb4, 0x45, 0xe7, 0x54, 0x8d, 0x2b, 0x63, 0x35, 0x69, 0x11, 0xef, 0x63,
	0xfe, 0xc9, 0x60, 0x6e, 0xac, 0x36, 0xda, 0xa9, 0x77, 0x71, 0x0d, 0xd1, 0x16, 0x9b, 0x7a, 0x4b,
	0x92, 0x65, 0xac, 0xe0, 0xe5, 0x3e, 0x89, 0x2b, 0x98, 0x59, 0xdd, 0xed, 0x36, 0x72, 0x92, 0xb1,
	0x22, 0x2d, 0x7f, 0x82, 0xb8, 0x81, 0x05, 0x35, 0x2d, 0x3a, 0x52, 0xad, 0x91, 0xd3, 0xf0, 0xc3,
	0x58, 0x08, 0x01, 0x7c, 0xa3, 0x48, 0x49, 0x9e, 0xb1, 0xe2, 0xbc, 0x0c, 0xdf, 0x22, 0x87, 0xd4,
	0x74, 0xd5, 0xfa, 0x0d, 0xfb, 0x75, 0xd5, 0x13, 0x3a, 0x39, 0x0b, 0x30, 0x31, 0x5d, 0xf5, 0x82,
	0xfd, 0xb3, 0xaf, 0xfc, 0xa9, 0xae, 0xa9, 0x77, 0x8a, 0x3a, 0x8b, 0x32, 0x0a, 0x7c, 0x2c, 0xf2,
	0x2f, 0x06, 0xfc, 0x43, 0x13, 0x8a, 0x5b, 0xe0, 0xd4, 0x1b, 0x0c, 0x83, 0x5e, 0x3c, 0x5e, 0xae,
	0x06, 0x3d, 0x0f, 0x3d, 0x28, 0x03, 0x3e, 0x30, 0x9a, 0xfc, 0x6d, 0x34, 0xfd, 0xd7, 0x88, 0x1f,
	0x1b, 0x3d, 0x8c, 0x9b, 0x0a, 0x83, 0x27, 0x07, 0xd7, 0x0e, 0xa0, 0x1c, 0x97, 0xf9, 0x4b, 0x36,
	0x3a, 0x21, 0x1b, 0x1f, 0xc9, 0xde, 0xdf, 0xc1, 0x7c, 0xd0, 0x11, 0x09, 0xc4, 0xc6, 0xa2, 0x8f,
	0xcb, 0x33, 0x91, 0xc2, 0xc2, 0x58, 0x7c, 0xd5, 0x6d, 0xdb, 0xd0, 0x92, 0x55, 0x51, 0x78, 0xd3,
	0xa7, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x21, 0x1c, 0x8d, 0xe4, 0x01, 0x00, 0x00,
}
